### ISSUE TITLE
limb_dark in fit_par.txt does not do anything

### ISSUE THREAD

**Issue by sebastian-zieba** [sebastian-zieba/PACMAN#15]
The fit_par.txt file in https://github.com/sebastian-zieba/PACMAN/blob/master/src/pacman/data/run_files/fit_par.txt still has the deprecated limb_dark parameter in it, which was moved into the pcf.
The docs fit_par has it correctly.

**Comment by gapp-c** [comment]
Thanks for pointing that out, I was wondering what that parameter does! Good to know I can just delete it from the fit_par file.

**Comment by sebastian-zieba** [comment]
This was fixed with commit acc314c and is now correct in version 0.4.0. Closing this issue.
