### ISSUE TITLE
Fitting the Light Curves documentation: Model calculation

### ISSUE THREAD

**Issue by gapp-c** [sebastian-zieba/PACMAN#18]
In the Fitting the Light Curves Documentation, the fit parameters corresponding to each model are given, but the exact meaning of many of the listed parameters is ambiguous since many of them are given in abbreviations only and without units. I think more descriptions of the fit parameters are needed. Also, for the models with analytical expressions (such as model_ramp), I think it'd be useful to state the equation of the model for clarification of the parameters' meanings.

**Comment by sebastian-zieba** [comment]
The units and meaning of most parameters are now explained. The formulae can be checked out in the respective python files.
