### ISSUE TITLE
Issue with TOI-1201 data optimal extraction

### ISSUE THREAD

**Issue by mar-palt** [sebastian-zieba/PACMAN#21]
Hi Sebastian. I've come across an issue when running stage 20 with TOI-1201 data: the output of the white light curve and spectroscopic light curve spectra contained in files lc_spec.txt and lc_white.txt produce "nan" for spec_opt and var_opt. I think it is an issue with the optimal extraction algorithm, but I can't figure out how to resolve it. I am attaching a screenshot of the lc_white.txt file. I haven't changed the code at all, and the pipeline still works great for GJ-1214 data, producing no such "nans". 

<img width="901" alt="Screen Shot 2023-10-11 at 10 56 14 AM" src="https://github.com/sebastian-zieba/PACMAN/assets/145788215/a43d6150-eea1-4a7b-a5bd-4861f1b4ead4">

**Comment by sebastian-zieba** [comment]
Also: If you planning to make a couple of s20 runs just to see if lc_white.txt changed, I'd suggest deactivating the saving of the s20 plots because that takes lots of time. (Especially save_utr_plot and save_bkg_hist_plot take up lots of runtime)
Hope that helps!

**Comment by mar-palt** [comment]
Hi Sebastian,

Thanks for your quick reply! I tried both sig_cut = 10 and 20, and both nsmooth = 7 and 11, but neither of them changed anything. I still have "nans" in my lc_spec.txt and lc_white.txt files.

**Comment by sebastian-zieba** [comment]
Hi @mar-palt ,
Hmm okay! Could you post one of the optimal extraction diagnostic plots here? They should be in s20_optextr

**Comment by sebastian-zieba** [comment]
Thanks! Yeah something is weird here. Could you also send me one of the following plots each: 

workdir/figs/s20_refspec_fit/refspec_fit_0.png

workdir/figs/s20_sp1d/sp1d_0.png

workdir/figs/s20_sp2d/sp2d_0.png

workdir/figs/s20_trace/trace_0.png

workdir/figs/s20_utr/utr0-0.png
.

**Comment by mar-palt** [comment]
![image](https://github.com/sebastian-zieba/PACMAN/assets/145788215/68bfee63-cac0-4bd0-ace4-dea015ac0892)

![image](https://github.com/sebastian-zieba/PACMAN/assets/145788215/4bfc586e-652c-439d-8cb1-1b018ef6fdb3)

![sp2d_0](https://github.com/sebastian-zieba/PACMAN/assets/145788215/7566f412-36d1-4fa7-b1ae-44ed0126650d)

![trace_0](https://github.com/sebastian-zieba/PACMAN/assets/145788215/6c409152-2802-4590-a90b-1ed4385eb8fd)

![utr0-0](https://github.com/sebastian-zieba/PACMAN/assets/145788215/d0ba0744-21d0-477f-a7a4-ab751a9a6468)

**Comment by sebastian-zieba** [comment]
Thanks! I see you're using the smaller subarray. Just double checking, is your rmin and rmax in the pcf set to:
rmin                         5
rmax                         261

**Comment by mar-palt** [comment]
Yes, rmin and rmax are set to 5 and 261 respectively. Thanks!

**Comment by sebastian-zieba** [comment]
Okay good! Can you also send me the plots in workdir/figs/s10_images?

**Comment by mar-palt** [comment]
![di_0](https://github.com/sebastian-zieba/PACMAN/assets/145788215/043c2bf6-696c-4ffb-a015-938d18076274)

![quick_di0](https://github.com/sebastian-zieba/PACMAN/assets/145788215/8ef52db2-af6d-4dd7-a8bd-e2dcf1b992ff)

Sidenote: there is only one direct image per visit, and only one visit

**Comment by sebastian-zieba** [comment]
Okay! Yeah, that actually might be a mistake related to how PACMAN calculates the position of the trace. You can see in the trace plot how the yellow line (the trace) doesn't overlap with the spectrum at all. I will have a look into that tomorrow. 
If you want a quick fix, you can set the position of the extraction window yourself in the code. You would only have to modify line 90 and 91 in s20_extract.py for that. By looking at the 2D spectrum by eye, it looks like it goes from approximately 50 to 220. So just change the code to `cmin = 50` and `cmax = 220`. I think that might fix the nan problem for now.

Just double checking: 
- the star of interest, is the one around pixel position (140,140) in the direct image?
- is the data from the SPACE program? (so that I am sure that I'm downloading the correct data tomorrow haha)

**Comment by mar-palt** [comment]
Thanks! The star of interest is the one around (140,140) and the data is taken from the SPACE program!
