### ISSUE TITLE
Issue with TOI-561 data: Stage 20

### ISSUE THREAD

**Issue by mar-palt** [sebastian-zieba/PACMAN#24]
Hi Sebastian! I am trying to run TOI-561 data that recently became available on MAST (proposal ID = 17192), but I'm running into an error at stage 20. I am attaching a screenshot of the error. 
<img width="569" alt="Screen Shot 2023-11-17 at 11 16 44 AM" src="https://github.com/sebastian-zieba/PACMAN/assets/145788215/e4e1ef00-3fff-4967-b5f3-8d5d9993877c">

The issue with the particular dataset is that the guide star was lost halfway through the observation, and then recovered. The result was that some of the images did not contain a spectrum, and some of them did contain a spectrum, but it was off-centered. Even after I removed these images from the data directory, I am still getting the same error.

**Comment by mar-palt** [comment]
Hi again! I think it might have something to do with how PACMAN is finding the trace. I had the same issue with TOI-1201, it seems to not be able to find the trace correctly for most targets in the 17192 program. I have trted changing cmin and cmax in the code, but that didn't change anything: the trace was still incorrect and the error was still present. I'm uploading an image of the trace as well. 

![trace_0](https://github.com/sebastian-zieba/PACMAN/assets/145788215/aec6be42-65b7-4594-ae6b-98ab1b9d2a1e)

**Comment by n-bachmann** [comment]
Hi, I had a similar problem with a different data set and found a solution for which I put in a pull request. In my case the coordinate of the reference pixel ('CRPIX' in the file header) wasn't the same for the direct and the spectral images. To account for that, I had to modify the code for stage 10 where the offset is set. I just changed the variables 'LTV1' and LTV2' to: 
LTV1 = ima[1].header['LTV1'] + int(abs(ima[1].header['CRPIX1'] - sp[1].header['CRPIX1']))					
LTV2 = ima[1].header['LTV2'] + int(abs(ima[1].header['CRPIX1'] - sp[1].header['CRPIX1']))
For that to work you have to load one spectral image before: 
files_sp = meta.files_sp     # spectra files
sp = fits.open(files_sp[0])  # opens first spectral file
This than also modifies the cmin and cmax in stage 20 and I got the right trace position in the end. 
Maybe this will work for your data too.

**Comment by sebastian-zieba** [comment]
Oh that's great! 
Perfect! I will test it on some other datasets in the next few hours and update PACMAN to a new version. 

@mar-palt , for the new fit problem you mentioned, could you create a new issue? This issue here will be closed after I merge the PR by @n-bachmann . In the new issue, please also attach your pcf and fit_par file. Thanks!
