### ISSUE TITLE
TOI-561 Stage 30 error

### ISSUE THREAD

**Issue by mar-palt** [sebastian-zieba/PACMAN#25]
Hi Sebastian, 

When I try running Stage 30 with TOI-561 data, I get the following error for both the white and spectroscopic light curve fits:

<img width="563" alt="Screen Shot 2023-11-21 at 12 27 04 PM" src="https://github.com/sebastian-zieba/PACMAN/assets/145788215/f6ad39e2-74b6-4939-8795-3fc5f1166455">

These are my pcf and fit_par files:
[fit_par.txt](https://github.com/sebastian-zieba/PACMAN/files/13429484/fit_par.txt)
[obs_par.pcf.txt](https://github.com/sebastian-zieba/PACMAN/files/13429504/obs_par.pcf.txt)

**Comment by n-bachmann** [comment]
Hi mar-palt, 
I got the same error message and found a solution which at least works for my dataset. My data has just one visit so there is no reason to not tie any of the parameters in the fit_par.txt file. Once I removed all the duplicated lines in the file and tied the parameters, the error in stage 30 was resolved. Maybe this could work for your dataset too.

**Comment by sebastian-zieba** [comment]
Hi @mar-palt , just double checking, do you have one or two visits?

**Comment by mar-palt** [comment]
Hi both, 

Sorry for the late response! I have only one visit, and I tried incorporating @n-bachmann's solution and it seems to work, the error isn't present any more. Thank you for you help!

**Comment by sebastian-zieba** [comment]
Hi @mar-palt ,

Great that it's fixed! 
Just for clarification: If you only have one visit, all values in the "tied" column in fit_par.txt should be "-1" and the lines shouldn't be repeated.  Only if you have several visits and you don't want to have the same value across visits (= you dont want to have them tied across visits), then you would repeat the line.
So for example, let's assume you have three visits. Then you will want to have a different normalization for each visit. In the fit_par.txt it will look something like this:

c              False   0      8.37        True     6.0       True     8.9      U       6.7       7.0      0.001      
c              False   1      8.37        True     6.0       True     8.9      U       6.7       7.0      0.001      
c              False   2      8.37        True     6.0       True     8.9      U       6.7       7.0      0.001      

This will give you one "c" value for each visit.
Hope that clarifies it a bit!

**Comment by sebastian-zieba** [comment]
This is fixed.
