### ISSUE TITLE
Error when running Stage 30 (spec) on my own data

### ISSUE THREAD

**Issue by mm-murphy** [sebastian-zieba/PACMAN#7]
Hello,

I'm trying out PACMAN on my own WFC3/G141 data set, and run into the following attribute error when I get to fitting the spectroscopic light curves in Stage 30. 

> (pacman) mmmurphy@ilus:~/inquiry/hd219666b/pacman$ python pacman_script.py --s30
workdir:  ./run_2022-12-12_15-54-19_hd219666b/
eventlabel:  hd219666b
Successfully reloaded meta file
Starting s30
Spectroscopic light curve fit(s) will be performed
using most recent s21 run: ./run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52
Identified file(s) for fitting: ['./run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.151.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.183.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.214.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.246.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.278.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.309.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.341.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.373.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.404.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.436.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.468.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.499.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.531.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.563.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.594.txt', './run_2022-12-12_15-54-19_hd219666b//extracted_sp/bins16_2022-12-13_12-38-52/speclc1.626.txt']

> ****** File: 1/16
> 
> 
> Removed 4 exposures because they were the first exposures in the orbit.
> Removed 16 exposures because they were the first orbit in the visit.
> median log10 raw flux: 6.77944412410621
> The highest amount of exposures in an orbit is 16
> Number of free parameters:  6
> Names of free parameters:  ['rp', 'c', 'v', 'r1', 'r2', 'scale']
> The predicted rms is 158.67
> 
> *STARTS LEAST SQUARED*
> Runs MPFIT... 
> rp_0 	 4.1487e-02 	 6.2156e-04
> c_0 	 6.7778e+00 	 4.1090e-05
> v_0 	 -1.2749e-06 	 2.8505e-07
> r1_0 	 7.3465e-02 	 1.7971e-02
> r2_0 	 6.8390e+00 	 8.4698e-02
> scale_0 	 1.0447e-02 	 4.6646e-05
> rms, chi2red =  141.2989683522296 0.9069527852844692
> ['rp', 'c', 'v', 'r1', 'r2', 'scale']
> 
> *STARTS MCMC*
> Runs MPFIT... 
> rp_0 	 4.1487e-02 	 6.2156e-04
> c_0 	 6.7778e+00 	 4.1090e-05
> v_0 	 -1.2749e-06 	 2.8505e-07
> r1_0 	 7.3465e-02 	 1.7971e-02
> r2_0 	 6.8390e+00 	 8.4698e-02
> scale_0 	 1.0447e-02 	 4.6646e-05
> rms, chi2red =  141.2989683522296 0.9069527852844692
> Run emcee...
>   0%|                                                                                                                                                                        | 0/6000 [00:00<?, ?it/s]/home/mmmurphy/anaconda3/envs/pacman/lib/python3.9/site-packages/emcee/moves/red_blue.py:99: RuntimeWarning: invalid value encountered in double_scalars
>   lnpdiff = f + nlp - state.log_prob[j]
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6000/6000 [00:20<00:00, 291.46it/s]
> Traceback (most recent call last):
>   File "/home/mmmurphy/inquiry/hd219666b/pacman/pacman_script.py", line 139, in <module>
>     main()
>   File "/home/mmmurphy/inquiry/hd219666b/pacman/pacman_script.py", line 135, in main
>     meta = s30.run30(eventlabel, workdir)
>   File "/home/mmmurphy/pipelines/PACMAN/src/pacman/s30_run.py", line 146, in run30
>     val_mcmc, err_lower_mcmc, err_upper_mcmc, fit = mcmc_fit(data, model, params, f, meta, fit_par)
>   File "/home/mmmurphy/pipelines/PACMAN/src/pacman/lib/mcmc.py", line 111, in mcmc_fit
>     util.append_fit_output(fit, meta, fitter='mcmc', medians=medians)
>   File "/home/mmmurphy/pipelines/PACMAN/src/pacman/lib/util.py", line 868, in append_fit_output
>     meta.chi2_notrescaled_list_mcmc.append(round(fit.chi2_notrescaled, precision))
> AttributeError: 'Model' object has no attribute 'chi2_notrescaled'
> 

I did not run into this error when doing the quickstart tutorial on the GJ 1214 data, which ran fine. I also did not run into this when fitting the white light curve for my data. Thanks in advance for any help you can provide!

**Comment by sebastian-zieba** [comment]
Hi, sure! I'll check that out!
Could you also send me the contents of your pcf and fit_par files?

**Comment by mm-murphy** [comment]
Of course, here are my pcf and fit_par files attached. Github wouldn't let me attach the pcf file as a .pcf, so I just converted the file extension to a .txt here which you should be able to convert right back without it changing anything inside. 

[fit_par.txt](https://github.com/sebastian-zieba/PACMAN/files/10222259/fit_par.txt)
[obs_par.txt](https://github.com/sebastian-zieba/PACMAN/files/10222277/obs_par.txt)

**Comment by sebastian-zieba** [comment]
Hi, the latest pushes should have fixed this bug. 
After adding "rescale_uncert_smaller_1" to your pcf and updating your code you should be good to go.
Let me know if you still run into this problem after all though!

**Comment by mm-murphy** [comment]
Hi Sebastian, I am very sorry for the delayed response. After updating my installation and adding that line to my pcf, it seems to work and I'm able to run Stage 30 to completion. Thank you for tracking down and fixing this bug!!

**Comment by sebastian-zieba** [comment]
Hi @mm-murphy, glad to hear! Thanks for the update!
If you run into other problems, I'm happy to help.

**Comment by sebastian-zieba** [comment]
Closing this issue
