### ISSUE TITLE
Problem with trace in GRISM512 subarray

### ISSUE THREAD

**Issue by brackham** [sebastian-zieba/PACMAN#9]
Thank you for this super-helpful pipeline! I'm having an issue reducing a WFC3/G141 dataset taken with the `GRISM512` subarray, and I think the trace step is the culprit.

I've reduced the example GJ1214 dataset, and the trace step behaves as expected.

![trace_5](https://user-images.githubusercontent.com/16804223/221298746-4b64d5c4-d1e9-4058-9187-0d44b2edac45.png)

However, when I try to apply the pipeline to a transit observation of HD189733 (Program 12881, Visit 11), I haven't been able to extract the spectrum. This is what a typical trace image looks like:

![trace_9](https://user-images.githubusercontent.com/16804223/221299072-5c2148e6-5ea0-4073-9daf-15c2dfb2b41c.png)

(The brightest spectrum in the top middle is the first-order spectrum of HD189733A, the second-order spectrum is to the right, and the spectrum of the fainter companion HD189733B is below.)

The star is correctly identified in the direct image, but as you can see from the position of the yellow trace line, the pipeline is looking for the spectrum in the wrong part of the chip.

![di_0](https://user-images.githubusercontent.com/16804223/221299530-6518ba51-d5d6-4409-88c7-9f682f2f3248.png)

I haven't noticed any parameters in the `.pcf` file that I can tweak to change this, so my best guess is that this is a bug with how the pipeline handles the `GRISM512` subarray versus the `GRISM256` one. Sorry if I missed something!

**Comment by sebastian-zieba** [comment]
Hi @brackham ,
sorry for the late response! I got buried in some JWST data analysis.

That's really interesting! I haven't seen that before! I have used PACMAN with GRISM512 data before and it worked well.

Is the data publicly available? If so, I could have a closer look at that later next week.

**Comment by brackham** [comment]
Hi @sebastian-zieba, thanks for the package and for taking a look at this!

Yes, the HD189733 data from Program 12881 are publicly available. I've also tried reducing a newer HD189733 dataset (Program 16180) and see the same issue. So far, I've managed to reduce them with PACMAN by hard-coding offsets to the `LTV1` and `LTV2` parameters taken from the headers.

If you can identify any insights into why some `GRISM512` datasets need this, that would be great!

**Comment by sebastian-zieba** [comment]
Hi @brackham , okay interesting! Thanks for the update and for raising this issue! 
I had a quick look at the files on MAST but couldn't identify anything which caught my eye and might cause problems with PACMAN. I'll check out these two datasets sometime at the end of next week. Thanks again!
Out of curiosity: The spectrum for the 12881 data seems to be at the edge of the detector (and not centered like the 16180 data). Do you know why?

**Comment by brackham** [comment]
The paper (McCullough et al. 2013, https://ui.adsabs.harvard.edu/abs/2014ApJ...791...55M/abstract) notes that this was just due to a miscalculation:

> As noted in the Introduction, the spectra were obtained in spatial scanning mode. We interleaved scanning first forward and then reversing direction, obtaining 16 forward–reverse pairs of exposures in each orbit. We had intended to locate the target on the detector such that its first-order spectrum would be entirely within a region read from a single amplifier; however, we miscalculated and the first-order spectrum crosses an amplifier boundary (at physical column 512) corresponding to λ = 1.55μm. A similar miscalculation caused the spectrum to scan off the top of the subarray and hence some of the samples were lost.

It was still the early days for the spatial scanning mode, I guess.

**Comment by sebastian-zieba** [comment]
I uploaded the fixes.
This issue should now be fixed with the latest version (v0.3.1).
Thanks a lot @brackham !

**Comment by brackham** [comment]
Thanks, @sebastian-zieba! This looks awesome. I will upgrade to `v0.3.1`, test out your solutions, and then close this issue!

**Comment by sebastian-zieba** [comment]
Awesome! Thanks!

**Comment by sebastian-zieba** [comment]
This issue should be fixed since v0.3.1. Closing.
